### PR TITLE
JENKINS-32394: Fix Changeset number display for Delivery Pipeline

### PR DESCRIPTION
**Pull request by olivierdagenais**
Slight improvement of #76.

Manual testing
--------------

1. Install the [Delivery Pipeline Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Delivery+Pipeline+Plugin).
2. Create a new job called **JENKINS-32394**
    1. Check the **Delivery Pipeline configuration** box and configure as follows:
        1. *Stage Name*: **Development**
        2. *Task Name*: **Build**
        3. *Customize Task Description Template*: **Build #${BUILD_NUMBER} on ${NODE_NAME}**
    2. Select **Team Foundation Server** under *Source Code Management* and configure to get source code from a TFVC project.
    3. Add a build step just to see the build doing something.  I used **Execute Windows batch command** set to `dir /s`
    4. Click **[Save]**
3. Click **Build Now** on the new job.
4. Go to the Jenkins home and click the "+" on the top tab row to add a new view and configure as follows:
    1. *View name*: **Pipeline**
    2. Select **Delivery Pipeline View**
    3. Click **[OK]**
    4. Under *View settings*, check **Show commit messages**
    4. Under *Pipelines* > *Components*, click **[Add]** and configure as follows:
        1. *Name*: **Delivery**
        2. *Initial Job*: **JENKINS-32394**
    5. Click **[OK]**
5. Notice how there's the first build listed there.  Let's go create some changesets in source control and then come back to Jenkins.
6. Click **Build Now** on the new job a second time.
7. Before the changes from this branch/pull request were applied, the second build would show the "Changes" table with "null" as the changeset ID.  After these changes, the "Changes" table now shows the changeset IDs:

image

Mission accomplished!

### CODE REVIEW

**Comment by mosabua** [comment]
+1

**Comment by pskumar448** [comment]
@olivierdagenais 
Went through the steps and the outcome of this fix, It is as working expected.

**Comment by olivierdagenais** [comment]
Thank you, @pskumar448 for your contribution and your assistance in verifying the fix!

**Comment by pskumar448** [comment]
Thanks @olivierdagenais

**Comment by thpert** [comment]
Thanks a lot :-)

**Pull request merged**
