### PR TITLE
JENKINS-26841: Upgrade TFS SDK to version 12.0.2

### PR DESCRIPTION
**Pull request by mosabua**
This upgrades the TFS SDK to 12.0.2 by adding the new files from redist folder and updating the pom.

This builds fine at the moment. I still have to validate this. I am creating the pull request now as a heads up so that others can test as well. I will validate myself asap.

cc @olivierdagenais

### CODE REVIEW

**Comment by mosabua** [comment]
I also filed an issue now.. https://issues.jenkins-ci.org/browse/JENKINS-26841

**Comment by mosabua** [comment]
Tested this now on our dev instance server with TFS 2013 update 4 and it works like a charm.

**Comment by apemberton** [comment]
Question: are these changes backward compatible w/TFS 2010 etc?

**Comment by olivierdagenais** [comment]
I had been hesitating to upgrade the TFS SDK because I thought TFS 2010 support had been dropped, but according to the [Download Microsoft Team Explorer Everywhere 2013](http://www.microsoft.com/en-us/download/details.aspx?id=40785) page, version 12.0.2 (published 2014/09/21):

> Works with Visual Studio Team Foundation Server 2010, Visual Studio Team Foundation Server 2012, Visual Studio Team Foundation Server 2013, and Visual Studio Online.

...but I haven't installed TFS 2010 to verify.

**Comment by olivierdagenais** [comment]
FYI, I haven't forgotten you.  I was testing your changes this morning when I noticed that @ndeloof's bd98b91ea614c307a6bb1e0af36d9dd2a5646e29 introduced a defect whereby upgrading the plugin breaks authentication for all jobs that use the TFS plug-in.  I'll have to fix _that_ first.

**Comment by mosabua** [comment]
No worries. I only have sporadic times to work on this. Next time will probably be in March.. but I will get a bunch of changes to you.

**Comment by olivierdagenais** [comment]
I fixed the upgrading defect; I also want to fix another in the "get-by-label" functionality for release 3.3.0.

I'll merge your changes for release 3.4.0.

**Comment by olivierdagenais** [comment]
Oops, I meant 3.2.0 and 3.3.0, respectively.

**Comment by mosabua** [comment]
Sounds good. I am still working on a few more pull requests. I would be good to merge some of the others that are open as well.

**Comment by olivierdagenais** [comment]
I rebased your branch as the `pr-30` branch (there was a minor conflict in `.gitignore`) and ran my integration tests on TFS 2012, 2013 and 2015:  all passed.

I'm good with merging this, although, since then, version 14.0.1 of the TFS SDK for Java has been released.  I'll go test upgrading to *that* and report back here; we may just want to skip directly to it, although upgrading to 12.0.2 first, and then to 14.0.1 separately would give us a better chance to isolate any defects coming from [our use of] the TFS SDK.

**Comment by olivierdagenais** [comment]
OK, 971051e5568288933feab67ea73916cb74ed8a4c (in the `update_tfs_sdk_14.0.1` branch) has the upgrade to version 14.0.1 of the Java TFS SDK and passes the integration tests.


Suggestions as to the course of action?

Plan A: upgrade to 12.0.2, publish a release candidate, upgrade to 14.0.1 and publish a second release candidate.

Plan B: upgrade to 14.0.1 and publish a release candidate.

The release candidates would be for interested users to soak test in staging environments, for, say, a week or two.

**Comment by mosabua** [comment]
I would not bother with 12.0.2 assuming that 14.0.1 is backward compatible with the same TFS server versions.

**Comment by olivierdagenais** [comment]
I have created pull request #45.  Feel free to close this one.

**Pull request closed without merging**
