### PR TITLE
Local workspaces are supported.

### PR DESCRIPTION
**Pull request by cgnuechtel**
Hi there,

if anybody is interested in: I have been implemented local workspaces for the Jenkins TFS plugin.
The implementation is covered by unit tests.
The code is based on the latest release version (3.1.1) and produces merge conflicts in recent versions.
The feature works in production on our Jenkins server.
You may enable it with the local-workspaces checkbox on the advanced options.
The default is still the using of server workspace.

It makes handling of workspaces easier since you do not have to deal with read-only files, etc.

Cheers
Christian

### CODE REVIEW

**Comment by olivierdagenais** [comment]
Thanks for the pull request; it looks like my recent changes around the password scrambling/encrypting are the source of conflicts.  I'll take care of it.

I'm scheduling adaptation and merge of your changes for release 3.4.0.

**Comment by olivierdagenais** [comment]
Oops, I meant 3.3.0.

**Comment by mosabua** [comment]
+1 of getting this merged. Could we add a global configuration for this as well? E.g. we have hundreds of jobs and would like to use the local workspace without having to configure them all manually.

**Comment by cgnuechtel** [comment]
@mosabua: Sorry for the late answer and thank you very much for your feedback.

I have been implemented your requested feature in the branch of this pull request. The feature is not yet used in production, but I verified it by unit and manual tests on a Jenkins developer instance.

@olivierdagenais: Hopefully, the feature is not hard to merge. Please let me know, if it is feasible to support you on resolving the merge conflict.

**Comment by cgnuechtel** [comment]
The feature is running in production from today on our company. I have been implemented some minor improvements and some small bug fixes. The work on that feature should be finished now.

**Comment by Leow88** [comment]
So there will not be any local workspace support?

**Comment by mosabua** [comment]
We need this feature ourselves as well and I am going to work towards merging for the next release hopefully.

**Comment by apieraf** [comment]
I would like to have this feature in the next version of the plugin, thanks

**Comment by s2oBCN** [comment]
+ I would like to have this feature in the next version of the plugin too, thanks !

**Comment by allenrice** [comment]
This is currently keeping us from upgrading at the moment

**Comment by ytterx** [comment]
Any progress on this feature?

**Comment by cgnuechtel** [comment]
I think that code is outdated and will not be required anymore... It is using the old command line API?!

**Pull request closed without merging**
