### PR TITLE
[JENKINS-34446] Fix bug - TFS PLUGIN environnement variables in project path

### PR DESCRIPTION
**Pull request by sylvainmouquet**
Fix the bug https://issues.jenkins-ci.org/browse/JENKINS-34446

### CODE REVIEW

**Comment by mosabua** [comment]
Looks good and would be great to have fixed in the upcoming release. Any objections to merge this @olivierdagenais and @DavidStaheli ?

**Comment by olivierdagenais** [comment]
Sorry for sitting on this for so long.

Thank you for your contribution!

**Comment by mosabua** [comment]
Awesome @olivierdagenais  .. I will verify this as well now.

**Comment by mosabua** [comment]
Verified on our test project for this usage and it works ;-)

**Comment by mosabua** [comment]
Also fixes https://issues.jenkins-ci.org/browse/JENKINS-30442 and a number of duplicate issues of this one.

**Comment by guilhermelabigalini** [comment]
I`m the original reporter of this issue, thanks a lot!!

**Pull request merged**
