### PR TITLE
[JENKINS-6933] Handle proxy settings

### PR DESCRIPTION
**Pull request by olivierdagenais**
# Background

This feature was originally submitted as pull request #66 and this branch improves upon the work by pulling the proxy configuration from Jenkins itself, adding tests and contributing a small fix to the polling feature, discovered while testing.

# Documentation

Here are the related changes submitted to document this new feature:

1. jenkinsci/jenkins#2060
2. Commit c04ea33a1bffbf36a8dfe952193489a40e20d673 in the `documentation_4.1.0` branch
3. [A proposed change to the JenkinsBehindProxy wiki page](https://groups.google.com/forum/#!topic/jenkinsci-dev/4nGCBozEGhc) 

# Manual testing

1. Set up a proxy server on the LAN.
    1. In my case, I installed [Polipo](http://www.pps.univ-paris-diderot.fr/~jch/software/polipo/) on my Jenkins master.  It's listening on all interfaces at port `8123`.
2. Upload private build of TFS plugin HPI to the Jenkins master via `/jenkins/pluginManager/advanced`, _Prepare for Shutdown_ via `/jenkins/quietDown` then restart Jenkins.
3. Configure one of the Jenkins agents to be unable to reach websites without going through a proxy server.
    1. In my case, it's an Ubuntu Linux 14.04 LTS VM for which I blanked out the `003 Router` (gateway) option in its DHCP reservation.  `wget` was unable to fetch anything ("No route to host.") until I [temporarily] set the `http_proxy` environment variable.
4. Create a Jenkins job to use the "Team Foundation Server" SCM with a URL that's not on the LAN and then "pin" the job to the aforementioned agent.
    1. In my case, I used a free [Visual Studio Team Services](https://www.visualstudio.com/products/visual-studio-team-services-vs) account that already had some TFVC repositories.
5. Launch the job in Jenkins, wait for the TFS SDK to time out in its attempts to connect (about 90 seconds due to the retries with exponential backoff) and then fail with the build with "No route to host".
6. Go to `/jenkins/pluginManager/advanced` to configure the proxy server in Jenkins.
7. Launch the job again and watch as the source code is downloaded.

Mission accomplished!

### CODE REVIEW

**Comment by mosabua** [comment]
Replaces https://github.com/jenkinsci/tfs-plugin/pull/66

**Comment by mosabua** [comment]
Should fix https://issues.jenkins-ci.org/browse/JENKINS-32166

**Comment by ytterx** [comment]
This fix builds upon my changes, and I have verified that it still works. Getting the proxy configuration by asking Jenkins itself deals with a small annoyance we still had by having to have a correct environment when starting a slave.

**Comment by olivierdagenais** [comment]
Thank you, @ytterx!  We couldn't have done it without you.!

**Pull request merged**
