### PR TITLE
Fixed repository browser URL persistence

### PR DESCRIPTION
**Pull request by mosabua**
Fixed https://issues.jenkins-ci.org/browse/JENKINS-30703

### CODE REVIEW

**Comment by mosabua** [comment]
Tested with Jenkins instance from hpi:run as well as on standalone install of latest LTS.

**Comment by mosabua** [comment]
@olivierdagenais imho we can merge this. If you are okay with that I can do the related tasks in here and JIRA. Also let me know if you keep tab in the wiki or so for the next release.

**Comment by olivierdagenais** [comment]
This indeed persists the *Repository browser* **URL** field in the job's `config.xml` file.

**Comment by olivierdagenais** [comment]
Oh and if you're offering to update JENKINS-30703 and add a note in the wiki for the upcoming 4.1 release, yes, please! :)

**Comment by olivierdagenais** [comment]
Thank you for your contribution!

**Pull request merged**
