### PR TITLE
Overwrite when getting files

### PR DESCRIPTION
**Pull request by pescuma**
To avoid problems when files are changed during the build.

### CODE REVIEW

**Comment by mosabua** [comment]
Should this maybe be an option ?

**Comment by pescuma** [comment]
Is there any problem if it always override? I'd find it strange if one build depends on the changes made by the previous one, but maybe I'm missing something.

**Comment by mosabua** [comment]
I am not sure. But we are changing current behavior of the plugin so it might be safer as an option. No idea what all our users are up to..

**Comment by jpricketMSFT** [comment]
Hi @pescuma, I agree with @mosabua that this should probably be a global option. At least then users can change the behavior back if there is some kind of problem. The default should probably be for it to overwrite as you have suggested.
Thanks,
Jason

**Comment by pescuma** [comment]
I've agreed with @mosabua and I intended to implement this as a build option, but it kind of got lost. I'll create that option.

**Comment by pescuma** [comment]
@jpricketMSFT @mosabua Done

**Comment by mosabua** [comment]
I like it. Imho we should merge.

**Pull request merged**
