### PR TITLE
Add workspace cloaking

### PR DESCRIPTION
**Pull request by olivierdagenais**
This is a continuation of the work previously submitted as #28, #60 and #64.

@ajalexander and @watsonlu, (and maybe @mahsoud) if you wouldn't mind taking a look to make sure I preserved the intent of your changes, maybe also try to fetch 28d1dc0 to build the HPI and deploy it in a staging/test Jenkins instance?

In the meantime, I'll be testing parameterization of a cloaked path, since it was a special request and enough of a corner case that I want to make sure nothing implodes as a result.

### CODE REVIEW

**Comment by olivierdagenais** [comment]
I created a parameterized job called _Cloaking_ with a *Project path* of `$/jenkins/${module}` (it's the Jenkins source code I imported in a TFVC repo) and a *Cloaked paths* value of `$/jenkins/${module}/src/test`.  I ran a couple of builds, with different values for the `module` parameter; here's partial output from one with `maven-agent`:

```
Deleting workspaces named 'Hudson-Cloaking-MASTER' from computer 'OLIVIDA-Z440'...
Deleted 1 workspace(s) named 'Hudson-Cloaking-MASTER'.
Querying for remote changeset at '$/jenkins/maven-agent' as of 'D2016-01-15T14:13:04Z'...
Query result is: Changeset #4480 by 'JENKINS-CI\olivida' on '2015-08-08T20:21:45Z'.
Creating workspace 'Hudson-Cloaking-MASTER' owned by 'jenkinstfsplugin'...
Mapping '$/jenkins/maven-agent' to local folder 'C:\Users\olivida\oss\tfs-plugin\work\workspace\Cloaking' in workspace 'Hudson-Cloaking-MASTER'...
Cloaking '$/jenkins/maven-agent/src/test' in workspace 'Hudson-Cloaking-MASTER'...
Created workspace 'Hudson-Cloaking-MASTER'.
```

The following lines in the console did indeed NOT contain any files under `src/test` and this was confirmed with an inspection of the workspace folder `C:\Users\olivida\oss\tfs-plugin\work\workspace\Cloaking`.

Mission accomplished!

**Comment by ajalexander** [comment]
@olivierdagenais This does seem to preserve the intent of the changes as far as I can tell.

I do have a question though. The commit message for facd3707470359ff8cbc5d81fec054eb1dfd502b indicates switching from ';' delimited to '\n' delimited input. However, there are a couple places in the code that allow either ';' or '\n'. You intended to leave support for either as a delimiter?

**Comment by olivierdagenais** [comment]
> The commit message for facd370 indicates switching from ';' delimited to '\n' delimited input.

You're right, the first line of the commit message does make it sound like it's a permanent switch.  The subsequent lines explain that I am still allowing semicolons, in case someone had deployed a version of the plugin from one of the other pull requests:

> Newlines are the preferred delimiters but semicolons are still accepted
> to transition previous implementations.

...but, come to think of it, I also renamed `cloakPaths` to `cloakedPaths`, so that functionality probably won't get used as I had originally intended.  It's still possible for me to add support for upgrading from a semicolon-delimited `cloakPaths` to a newline-delimited `cloakedPaths`.  What would you prefer?  Rip out semicolon-related code or add `cloakPaths` import?

Thanks!
\- Oli

**Comment by mahsoud** [comment]
Its always nice to be backwards compatible.

From: Aaron Alexander
Sent: Monday, January 18, 2016 10:17 PM
To: jenkinsci/tfs-plugin
Reply To: jenkinsci/tfs-plugin
Cc: mahsoud
Subject: Re: [tfs-plugin] Add workspace cloaking (#68)



@olivierdagenais<https://github.com/olivierdagenais> This does seem to preserve the intent of the changes as far as I can tell.

I do have a question though. The commit message for facd370<https://github.com/jenkinsci/tfs-plugin/commit/facd3707470359ff8cbc5d81fec054eb1dfd502b> indicates switching from ';' delimited to '\n' delimited input. However, there are a couple places in the code that allow either ';' or '\n'. You intended to leave support for either as a delimiter?

-

**Comment by ajalexander** [comment]
@olivierdagenais I missed the last bit of that. Sorry for the mix-up.

I'd lean towards ripping out the semicolon support for a simpler code base. Missing backwards compatibility for an unreleased feature seems OK.

**Comment by olivierdagenais** [comment]
> Missing backwards compatibility for an unreleased feature seems OK.

Agreed!  I'll rip it out, probably tomorrow.

**Comment by olivierdagenais** [comment]
OK, I removed support for ';', updated the tests and improved the documentation.  I'll merge this pull request at end-of-day (17:00 Eastern Time, 22:00 UTC) if there are no objections.

**Comment by mahsoud** [comment]
We did some testing, it looks good. Thank you!

**Pull request merged**
