### PR TITLE
[FIXED JENKINS-16207] TFS 2012+ Links Fixed

### PR DESCRIPTION
**Pull request by DD202**
Fixed the merge issues with the last request. Option exists under the Adanced section to  use the REST style urls created with TFS 2012+

### CODE REVIEW

**Comment by olivierdagenais** [comment]
Sorry for the very long delay; when I first got commit access to this project, I had been only tackling my immediate needs at $DAYJOB.

I am planning to review these changes for release 3.3.0.

**Comment by mosabua** [comment]
I would love to get this one into a release soon! +1

**Comment by mosabua** [comment]
@olivierdagenais I was just checking the repo browser URL persistence on a real server and found that we need this merged for links to changesets and so on to actually work. Are you mostly okay with how this PR is implemented? If yes, I will clean it up into a separate branch and then test and merge it.

**Comment by mosabua** [comment]
Also might default the new parameter to true so that it will work out of the box for new TFS server installations..

**Comment by mosabua** [comment]
Given that we do not even support older versions out of the box I think this might be overkill. Instead of a config flag and so on we might want to just change the URL to use the new URLs. Can you confirm that these style URLs are used in all current versions? I will prepare a PR for this approach next.

**Comment by mosabua** [comment]
Replaced by https://github.com/jenkinsci/tfs-plugin/pull/71

**Pull request closed without merging**
