### PR TITLE
Allow users to map sub-folders of cloaked paths, part II

### PR DESCRIPTION
**Pull request by pvandervelde**
Reintroduce the code that allows mapping sub-folders of a cloaked path.

This PR is here because commit f6fe6de50a52e4c0fe3419b996bdc8204c912210 was reverted due to issues with the functional tests. Any changes to the code / tests will be applied to this PR.

### CODE REVIEW

**Comment by jpricketMSFT** [comment]
@pvandervelde I hope to have some time to try the tests out myself and do a little debugging this week.

**Comment by pvandervelde** [comment]
@jpricketMSFT Have you managed to find any time to have a look at the tests for this one? We're using it on our production server for a small number of builds and so far it is working. Would be good to figure out what is wrong with either the code or the tests so that we can merge this PR.

**Comment by jpricketMSFT** [comment]
@pvandervelde Sorry, I have pulled off of Jenkins to work on other things for the last couple months. hopefully @kelliejos can take a look at this soon.

**Comment by pvandervelde** [comment]
@kelliejos Any progress on this?

**Comment by pvandervelde** [comment]
@jpricketMSFT @kelliejos Has anybody had time to have a look at the integration test? We've been running with this in production for a bit now and haven't found anything weird yet.

**Comment by fuzzmz** [comment]
@keljos @oleg-nenashev can someone please take a look over this? It's a pretty important functionality from my point of view.

**Comment by oleg-nenashev** [comment]
Hi. I do not maintain thus plugin, and I have not been using TFS since
2012. I doubt my reviews here would be helpful

**Comment by pvandervelde** [comment]
Given that this has not been merged in over 4 years ...

**Pull request closed without merging**
